import { MovieCard } from "@/components/movie/MovieCard";
import { MovieCardSkelton } from "@/components/movie/MovieCardSkelton";
import useLoader from "@/Hooks/useLoader";
import { useQuery } from "@/Hooks/useQuery";
import { IMovie } from "@/interfaces/movie";
import { Select } from "@/ui/Select";
import axios from "axios";
import { GetServerSidePropsContext } from "next";
import Head from "next/head";
import { nanoid } from "nanoid";
import { useRouter } from "next/router";
import { Navbar } from "@/ui/Navbar";

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const { query } = context;
  const { ordering = "", limit = 25, search = "" } = query;
  const response = await axios.get(
    `http://localhost:7070/api/movies?limit=${limit}&ordering=${ordering}&search=${search}`
  );
  const { data } = response;
  return {
    props: { data },
  };
}

export default function Home({ data }: { data: IMovie[] }): JSX.Element {
  const movies = data;
  const router = useRouter();
  const { query } = router;
  const { ordering = "", limit = 24, search = "" } = query;
  const loading = useLoader();
  const { addquery, removeQuery } = useQuery();

  return (
    <>
      <Head>
        <title>My client project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-slate-100 min-h-screen">
        <div className="xl:container mx-auto">
          <div className="bg-white">
            <Navbar
              value={search}
              onchange={(e) => {
                addquery({ search: e });
                removeQuery({ search: e });
              }}
            />
            <Select
              items={[
                { value: "", label: "Sort..." },
                { value: "releasedAsc", label: "Oldest" },
                { value: "releasedDesc", label: "Newest" },
                { value: "imbdRatingDesc", label: "Most Popular" },
                { value: "titleAsc", label: "A-Z" },
                { value: "titleDesc", label: "Z-A" },
              ]}
              onchange={(e) => {
                addquery({ ordering: e.target.value });
              }}
              value={ordering + ""}
              itemLabel={"label"}
              itemValue={"value"}
            />
            <Select
              items={[
                { value: "6", label: "6" },
                { value: "12", label: "12" },
                { value: "24", label: "24" },
                { value: "48", label: "48" },
              ]}
              onchange={(e) => {
                addquery({ limit: e.target.value });
              }}
              value={limit + ""}
              itemLabel={"label"}
              itemValue={"value"}
            />

            <div className="p-4 grid grid-cols-6 gap-4">
              {!loading
                ? movies.map((movie) => (
                    <MovieCard movie={movie} key={movie._id} />
                  ))
                : Array.from(Array(limit), () => (
                    <MovieCardSkelton key={nanoid()} />
                  ))}
            </div>
          </div>
        </div>
      </div>
    </>
  );
}

// export async function getStaticProps() {
//   const response = await fetch(`http://localhost:7070/api/movies?limit=20`);
//   const data = await response.json();
//   return {
//     props: { movies: data },
//   };
// }
